version: '3.8'

services:
  backend:
    build: 
      context: ./Backend/
      dockerfile: Dockerfile.backend
    command: uvicorn src.main:app --reload --host 0.0.0.0
    restart: always
    ports:
      - 8008:8000
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./Backend/src:/code/src

  db:
    build:
      context: ./Database/
      dockerfile: Dockerfile.postgres
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always

  redis:
    image: bitnami/redis:latest
    restart: always
    expose:
      - 6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb
